#### The config file for lifelong class incremental learning with FGN.
#### For cora pubmed and citeseer we use the featBrd layer
dataset=cora
model=attnplain
device=cuda:0
seed=1

sample=10
jump=1
memory=512
opt=SGD
merge=1

hidden =[64, 64]
drop = [0.3, 0.1]