#### The config file for lifelong class incremental learning with FGN.
#### For cora pubmed and citeseer we use the featBrd layer
dataset=cora # pubmed
model=attnplain
device=cuda:0
seed=1

sample=10
jump=1
memory=512
batch=10
opt=SGD
lr=0.03
iteration=8

hidden =[64, 64]
drop = [0.3, 0.1]